title: Wasilat Olatinwo # your name (or website title) here
logo: "/images/IMG_6672.jpg?raw=true" # your photo (or logo) here
logo {
  border-radius: 50%;
}
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's degree data science student at the University of the West of England 

  Creating Possibilities through Data-Driven Insights 
  <br><br>
  <a href="https://www.linkedin.com/in/olamide-olatinwo/"> LinkedIn</a>
  <a href="kanyinsola.mide@yahoo.com"> E-mail</a>
  
